@baseUrl = http://localhost:3000

################################################################################################
### POSTS – Emily
################################################################################################

### Create new post (Emily)
POST {{baseUrl}}/posts
Content-Type: application/json

{
  "sender": "Emily",
  "message": "This is my first post"
}

###

### Create another post (Dotan)
POST {{baseUrl}}/posts
Content-Type: application/json

{
  "sender": "Dotan",
  "message": "Hello from Dotan"
}

###

### Get all posts
GET {{baseUrl}}/posts

###

### Get posts by Emily
GET {{baseUrl}}/posts?sender=Emily

###

### Get post by id
# replace with a real id from one of the create responses
GET {{baseUrl}}/posts/691884fdf382a01bfec990f4

###

### Update post (change message by Emily)
PUT {{baseUrl}}/posts/691884fdf382a01bfec990f4
Content-Type: application/json

{
  "sender": "Emily",
  "message": "Updated message from Emily"
}




################################################################################################
### COMMENTS – Dotan
################################################################################################

### Create new comment (Dotan)
POST {{baseUrl}}/comments/691886656f4b34eec2d6acd9
Content-Type: application/json

{
  "sender": "Dotan",
  "message": "This is my first comment"
}

###

### Create another comment (Emily)
POST {{baseUrl}}/comments/691886656f4b34eec2d6acd9
Content-Type: application/json

{
  "sender": "Emily",
  "message": "This is my second comment"
}

###

### Get all comments for a post
GET {{baseUrl}}/comments/691886656f4b34eec2d6acd9

###
